/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    posts: Post;
    categories: Category;
    materials: Material;
    'material-categories': MaterialCategory;
    'material-files': MaterialFile;
    testimonials: Testimonial;
    leads: Lead;
    contracts: Contract;
    'contract-documents': ContractDocument;
    'email-segments': EmailSegment;
    'email-campaigns': EmailCampaign;
    'email-logs': EmailLog;
    'ad-campaigns': AdCampaign;
    'ad-groups': AdGroup;
    'ad-keywords': AdKeyword;
    'ad-metrics-daily': AdMetricsDaily;
    'ad-competitors': AdCompetitor;
    'system-links': SystemLink;
    'api-inventory': ApiInventory;
    'content-calendar': ContentCalendar;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    posts: PostsSelect<false> | PostsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    materials: MaterialsSelect<false> | MaterialsSelect<true>;
    'material-categories': MaterialCategoriesSelect<false> | MaterialCategoriesSelect<true>;
    'material-files': MaterialFilesSelect<false> | MaterialFilesSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    leads: LeadsSelect<false> | LeadsSelect<true>;
    contracts: ContractsSelect<false> | ContractsSelect<true>;
    'contract-documents': ContractDocumentsSelect<false> | ContractDocumentsSelect<true>;
    'email-segments': EmailSegmentsSelect<false> | EmailSegmentsSelect<true>;
    'email-campaigns': EmailCampaignsSelect<false> | EmailCampaignsSelect<true>;
    'email-logs': EmailLogsSelect<false> | EmailLogsSelect<true>;
    'ad-campaigns': AdCampaignsSelect<false> | AdCampaignsSelect<true>;
    'ad-groups': AdGroupsSelect<false> | AdGroupsSelect<true>;
    'ad-keywords': AdKeywordsSelect<false> | AdKeywordsSelect<true>;
    'ad-metrics-daily': AdMetricsDailySelect<false> | AdMetricsDailySelect<true>;
    'ad-competitors': AdCompetitorsSelect<false> | AdCompetitorsSelect<true>;
    'system-links': SystemLinksSelect<false> | SystemLinksSelect<true>;
    'api-inventory': ApiInventorySelect<false> | ApiInventorySelect<true>;
    'content-calendar': ContentCalendarSelect<false> | ContentCalendarSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'ads-settings': AdsSetting;
  };
  globalsSelect: {
    'ads-settings': AdsSettingsSelect<false> | AdsSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  slug?: string | null;
  /**
   * Texto curto exibido na listagem e no SEO.
   */
  excerpt?: string | null;
  coverImage?: (number | null) | Media;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  category?: (number | null) | Category;
  tags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  author?: (number | null) | User;
  status: 'draft' | 'published';
  /**
   * Datas futuras agendam a publicação.
   */
  publishedAt?: string | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
  };
  /**
   * Marcado automaticamente quando o e-mail de novo conteúdo é disparado aos assinantes da newsletter, ao publicar.
   */
  subscriberAlertSent?: boolean | null;
  likes?: number | null;
  dislikes?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    feature?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  slug?: string | null;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "materials".
 */
export interface Material {
  id: number;
  title: string;
  slug?: string | null;
  /**
   * Resumo curto exibido na listagem e no topo da página do material.
   */
  description?: string | null;
  /**
   * Texto rico exibido na página do material (abaixo do resumo). Importável do .md.
   */
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  coverImage?: (number | null) | Media;
  /**
   * Arquivo que o visitante baixa no site (PDF, Excel, Word, PPT, .md, ZIP…).
   */
  file: number | MaterialFile;
  kind?: ('ebook' | 'planilha' | 'template' | 'checklist' | 'guia' | 'apresentacao' | 'video') | null;
  category?: (number | null) | MaterialCategory;
  /**
   * Ex.: v1.0, 2026
   */
  version?: string | null;
  downloads?: number | null;
  featured?: boolean | null;
  status: 'draft' | 'published';
  publishedAt?: string | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
  };
  /**
   * Marcado automaticamente quando o e-mail de novo conteúdo é disparado aos assinantes da newsletter, ao publicar.
   */
  subscriberAlertSent?: boolean | null;
  likes?: number | null;
  dislikes?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "material-files".
 */
export interface MaterialFile {
  id: number;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "material-categories".
 */
export interface MaterialCategory {
  id: number;
  name: string;
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  name: string;
  role?: string | null;
  quote: string;
  photo?: (number | null) | Media;
  rating?: number | null;
  featured?: boolean | null;
  status: 'draft' | 'published';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: number;
  name: string;
  email: string;
  company?: string | null;
  /**
   * Número com DDD. Na lista vira link para conversar no WhatsApp.
   */
  whatsapp?: string | null;
  instagram?: string | null;
  /**
   * Aceita receber a newsletter/novos conteúdos.
   */
  wantsNewsletter?: boolean | null;
  /**
   * Aceita receber ofertas e campanhas promocionais.
   */
  wantsPromotions?: boolean | null;
  /**
   * Anotações internas sobre o lead (contexto, histórico, próximos passos).
   */
  notes?: string | null;
  source: string;
  details?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  consent?: boolean | null;
  /**
   * 0 = só o e-mail de resultado · 1–3 = e-mails da sequência já enviados (D+2, D+5, D+7).
   */
  nurtureStage?: number | null;
  /**
   * Marque quando o lead agendar a call, virar cliente ou pedir para não receber. O link de descadastro dos e-mails também marca isto.
   */
  nurtureOptOut?: boolean | null;
  nurtureLastAt?: string | null;
  /**
   * Descadastro do link 'Sair da lista' das campanhas manuais. Independente da nutrição pós-diagnóstico (nurtureOptOut).
   */
  marketingOptOut?: boolean | null;
  /**
   * Preenchido automaticamente por gclid/utm_campaign — pode ser corrigido à mão.
   */
  adCampaign?: (number | null) | AdCampaign;
  adGroup?: (number | null) | AdGroup;
  adKeyword?: (number | null) | AdKeyword;
  adGclid?: string | null;
  dealStatus?: ('em_andamento' | 'ganho' | 'perdido') | null;
  dealPackage?: ('nenhum' | 'essencial' | 'implementacao' | 'outro') | null;
  /**
   * Sobrepõe o valor padrão do pacote quando preenchido.
   */
  dealValue?: number | null;
  dealMonths?: number | null;
  dealClosedAt?: string | null;
  dealNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Campanhas do Google Ads (config + metas de orçamento/CPC). Preencher 'ID da campanha no Google Ads' quando a conta existir.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ad-campaigns".
 */
export interface AdCampaign {
  id: number;
  name: string;
  /**
   * Preencher quando a conta existir — usado pela sincronização automática e pela atribuição de leads via utm_campaign.
   */
  googleAdsCampaignId?: string | null;
  status?: ('rascunho' | 'ativa' | 'pausada' | 'encerrada') | null;
  dailyBudgetTarget?: number | null;
  monthlyBudgetTarget?: number | null;
  cpcCeiling?: number | null;
  startDate?: string | null;
  notes?: string | null;
  forecastClicks?: number | null;
  forecastImpressions?: number | null;
  forecastCost?: number | null;
  forecastCtr?: number | null;
  forecastAvgCpc?: number | null;
  forecastDailyBudget?: number | null;
  forecastCapturedAt?: string | null;
  forecastNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ad-groups".
 */
export interface AdGroup {
  id: number;
  campaign: number | AdCampaign;
  name: string;
  status?: ('ativo' | 'pausado') | null;
  rollupWindowDays?: number | null;
  rollupImpressions?: number | null;
  rollupClicks?: number | null;
  rollupCost?: number | null;
  rollupConversions?: number | null;
  rollupUpdatedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ad-keywords".
 */
export interface AdKeyword {
  id: number;
  campaign?: (number | null) | AdCampaign;
  adGroup?: (number | null) | AdGroup;
  text: string;
  isNegative?: boolean | null;
  negativeLevel?: ('ad_group' | 'campaign') | null;
  matchType: 'frase' | 'exata' | 'ampla';
  status?: ('ativa' | 'pausada' | 'candidata-negativa') | null;
  rollupWindowDays?: number | null;
  rollupImpressions?: number | null;
  rollupClicks?: number | null;
  rollupCost?: number | null;
  rollupConversions?: number | null;
  rollupUpdatedAt?: string | null;
  plannerVolume?: string | null;
  plannerCompetition?: ('sem_dados' | 'baixa' | 'media' | 'alta') | null;
  plannerTopBidLow?: number | null;
  plannerTopBidHigh?: number | null;
  plannerYoY?: string | null;
  plannerCapturedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Contratos gerados a partir do Gerador de Contratos (EA HUB) e enviados para assinatura eletrônica pelo link /assinar/[token].
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contracts".
 */
export interface Contract {
  id: number;
  /**
   * Gerado automaticamente a partir do tipo de contrato e do nome do cliente.
   */
  title?: string | null;
  status: 'rascunho' | 'enviado' | 'assinado' | 'cancelado';
  contractType: 'mentoria' | 'consultoria' | 'conselho' | 'diagnostico' | 'projeto';
  /**
   * Só para Mentoria e Consultoria.
   */
  horizonte?: ('trimestral' | 'semestral' | 'anual') | null;
  /**
   * Não se aplica ao Projeto Personalizado (usa projValorTotal).
   */
  valorMensal?: number | null;
  projNome?: string | null;
  projDescricao?: string | null;
  etapas?:
    | {
        nome?: string | null;
        prazo?: string | null;
        descricao?: string | null;
        id?: string | null;
      }[]
    | null;
  projDuracao?: string | null;
  projDataEntrega?: string | null;
  projValorTotal?: number | null;
  projParcelas?: number | null;
  projValorParcela?: number | null;
  tipoPessoa: 'PF' | 'PJ';
  pfNome?: string | null;
  pfCpf?: string | null;
  pjRazao?: string | null;
  pjFantasia?: string | null;
  pjCnpj?: string | null;
  pjRepNome?: string | null;
  pjRepCpf?: string | null;
  pjRepCargo?: string | null;
  clienteEndereco?: string | null;
  clienteEmail: string;
  clienteTelefone?: string | null;
  dataInicio?: string | null;
  diaVencimento?: number | null;
  formaPagamento?:
    | ('PIX' | 'Boleto bancário' | 'Transferência bancária (TED/DOC)' | 'Cartão de crédito recorrente')
    | null;
  clausulaReajuste?: boolean | null;
  temDiagnostico?: boolean | null;
  diagValor?: number | null;
  diagData?: string | null;
  diagForaPrazo?: boolean | null;
  bonusMesGratis?: boolean | null;
  bonusVisitaExtra?: boolean | null;
  bonusIndicacao?: boolean | null;
  indicacaoPerc?: number | null;
  bonusIsencaoMulta?: boolean | null;
  bonusParcelamento?: boolean | null;
  parcelamentoN?: number | null;
  paragrafoLivre?: string | null;
  localAssinatura?: string | null;
  dataAssinatura?: string | null;
  /**
   * Gerado pelo servidor a partir dos campos acima. Não editável diretamente.
   */
  contractHtml?: string | null;
  contractHash?: string | null;
  signToken?: string | null;
  /**
   * Gravado automaticamente a cada reenvio para um contato diferente do cadastrado no contrato.
   */
  additionalRecipients?:
    | {
        nome?: string | null;
        email?: string | null;
        telefone?: string | null;
        sentAt?: string | null;
        id?: string | null;
      }[]
    | null;
  signedAt?: string | null;
  signerIp?: string | null;
  signerNameConfirmed?: string | null;
  signerDocumentConfirmed?: string | null;
  /**
   * Deve ser idêntico a contractHash. Se divergir, o texto foi alterado após o envio.
   */
  signatureHashAtSigning?: string | null;
  /**
   * Marcado quando o nome ou documento digitado na assinatura divergia do cadastrado e o signatário confirmou explicitamente ser representante legal ou pessoa autorizada.
   */
  signerMismatchAcknowledged?: boolean | null;
  /**
   * Gerado automaticamente ao assinar. Contém o certificado e o contrato integral.
   */
  signedPdf?: (number | null) | ContractDocument;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contract-documents".
 */
export interface ContractDocument {
  id: number;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Critérios para selecionar leads por origem, pilar mais fraco e score do diagnóstico. Usado pelas Campanhas de e-mail.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "email-segments".
 */
export interface EmailSegment {
  id: number;
  name: string;
  description?: string | null;
  source?: ('any' | 'diagnostic' | 'newsletter' | 'popup' | 'download' | 'contact') | null;
  pillar?:
    | (
        | 'any'
        | 'Fluxo de Alta Performance'
        | 'Arquitetura do Crescimento'
        | 'Objetivos Estratégicos'
        | 'Métricas de Sucesso'
        | 'Gestão de Desafios'
        | 'Evolução Constante'
      )
    | null;
  scoreMin?: number | null;
  scoreMax?: number | null;
  createdFrom?: string | null;
  createdTo?: string | null;
  /**
   * Contagem em tempo real (e-mail válido + consentimento + não descadastrado + critérios acima). Recalculada sempre que a tela é aberta.
   */
  memberCount?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Escreva o conteúdo, escolha o segmento, salve como "Rascunho" para revisar e mude o status para "Agendada (enviar agora)" quando quiser disparar.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "email-campaigns".
 */
export interface EmailCampaign {
  id: number;
  subject: string;
  segment: number | EmailSegment;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  status?: ('rascunho' | 'agendada_envio' | 'enviando' | 'enviada' | 'erro') | null;
  statsTotal?: number | null;
  statsSent?: number | null;
  statsFailed?: number | null;
  statsStartedAt?: string | null;
  statsFinishedAt?: string | null;
  statsError?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Histórico de todo e-mail de nutrição/marketing enviado — não inclui as notificações internas de lead para a equipe.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "email-logs".
 */
export interface EmailLog {
  id: number;
  type:
    | 'diagnostic-result'
    | 'nurture-1'
    | 'nurture-2'
    | 'nurture-3'
    | 'campaign'
    | 'content-alert'
    | 'contract-sent'
    | 'contract-signed';
  status: 'sent' | 'failed';
  to: string;
  subject: string;
  lead?: (number | null) | Lead;
  campaign?: (number | null) | EmailCampaign;
  /**
   * resend · smtp · console (não configurado)
   */
  via?: string | null;
  errorMessage?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Uma linha por campanha por dia. Pode ser lançada manualmente (copiando do Google Ads) até a sincronização automática existir.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ad-metrics-daily".
 */
export interface AdMetricsDaily {
  id: number;
  campaign: number | AdCampaign;
  date: string;
  impressions?: number | null;
  clicks?: number | null;
  cost?: number | null;
  conversions?: number | null;
  source?: ('manual' | 'api') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Quem o Google mostra (anúncios e orgânico) nas buscas pelas palavras-chave da campanha.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ad-competitors".
 */
export interface AdCompetitor {
  id: number;
  name: string;
  domain?: string | null;
  /**
   * O termo buscado no Google em que este concorrente apareceu.
   */
  keywordText: string;
  type?: ('patrocinado' | 'organico' | 'local') | null;
  adTitle?: string | null;
  adSnippet?: string | null;
  appearances?: number | null;
  seenAt?: string | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Portfólio de sistemas da EA (cartão de visita). Deixe "URL" em branco para um card "em breve".
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "system-links".
 */
export interface SystemLink {
  id: number;
  name: string;
  /**
   * Endereço completo (https://...) ou rota interna (/eahub/...). Em branco = card “em breve”.
   */
  url?: string | null;
  description?: string | null;
  /**
   * Menor aparece primeiro.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Toda API/credencial externa usada por algum sistema da EA — provedor, sistema(s) consumidor(es), vencimento e faturamento.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "api-inventory".
 */
export interface ApiInventory {
  id: number;
  name: string;
  provider: string;
  category?: ('ia' | 'redes-sociais' | 'marketing' | 'email' | 'mensageria' | 'infra' | 'outro') | null;
  systems?:
    | {
        system: string;
        envVar?: string | null;
        active?: boolean | null;
        id?: string | null;
      }[]
    | null;
  status?: ('ativo' | 'bloqueado' | 'pendente' | 'dormente' | 'cancelamento') | null;
  expiresAt?: string | null;
  renewalCycle?: string | null;
  hasBilling?: boolean | null;
  billingType?: ('gratuito' | 'pre-pago' | 'pos-pago' | 'assinatura' | 'a-confirmar') | null;
  balanceOrCost?: string | null;
  balanceCheckedAt?: string | null;
  billingLink?: string | null;
  credentialLocation?: string | null;
  notes?: string | null;
  lastVerified?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Calendário de posts para Instagram, Facebook, YouTube e LinkedIn.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "content-calendar".
 */
export interface ContentCalendar {
  id: number;
  date: string;
  phase: 'prep' | 'semana-1' | 'semana-2' | 'semana-3' | 'semana-4';
  pillar: 'preparacao' | 'lancamento' | 'gestao' | 'vendas' | 'lideranca';
  channels?:
    | ('ig-feed' | 'ig-reels' | 'ig-stories' | 'facebook' | 'li-post' | 'li-artigo' | 'yt-shorts' | 'yt-video')[]
    | null;
  /**
   * Ex.: Carrossel (4 lâminas), Vertical 20-30s
   */
  format?: string | null;
  theme: string;
  /**
   * Blog/material de origem, quando houver.
   */
  sourceLabel?: string | null;
  copyIdea?: string | null;
  ctaOrAction?: string | null;
  status: 'planejado' | 'em-producao' | 'concluido';
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'materials';
        value: number | Material;
      } | null)
    | ({
        relationTo: 'material-categories';
        value: number | MaterialCategory;
      } | null)
    | ({
        relationTo: 'material-files';
        value: number | MaterialFile;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'leads';
        value: number | Lead;
      } | null)
    | ({
        relationTo: 'contracts';
        value: number | Contract;
      } | null)
    | ({
        relationTo: 'contract-documents';
        value: number | ContractDocument;
      } | null)
    | ({
        relationTo: 'email-segments';
        value: number | EmailSegment;
      } | null)
    | ({
        relationTo: 'email-campaigns';
        value: number | EmailCampaign;
      } | null)
    | ({
        relationTo: 'email-logs';
        value: number | EmailLog;
      } | null)
    | ({
        relationTo: 'ad-campaigns';
        value: number | AdCampaign;
      } | null)
    | ({
        relationTo: 'ad-groups';
        value: number | AdGroup;
      } | null)
    | ({
        relationTo: 'ad-keywords';
        value: number | AdKeyword;
      } | null)
    | ({
        relationTo: 'ad-metrics-daily';
        value: number | AdMetricsDaily;
      } | null)
    | ({
        relationTo: 'ad-competitors';
        value: number | AdCompetitor;
      } | null)
    | ({
        relationTo: 'system-links';
        value: number | SystemLink;
      } | null)
    | ({
        relationTo: 'content-calendar';
        value: number | ContentCalendar;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  coverImage?: T;
  content?: T;
  category?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  author?: T;
  status?: T;
  publishedAt?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
      };
  subscriberAlertSent?: T;
  likes?: T;
  dislikes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "materials_select".
 */
export interface MaterialsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  content?: T;
  coverImage?: T;
  file?: T;
  kind?: T;
  category?: T;
  version?: T;
  downloads?: T;
  featured?: T;
  status?: T;
  publishedAt?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
      };
  subscriberAlertSent?: T;
  likes?: T;
  dislikes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "material-categories_select".
 */
export interface MaterialCategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "material-files_select".
 */
export interface MaterialFilesSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  quote?: T;
  photo?: T;
  rating?: T;
  featured?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  company?: T;
  whatsapp?: T;
  instagram?: T;
  wantsNewsletter?: T;
  wantsPromotions?: T;
  notes?: T;
  source?: T;
  details?: T;
  consent?: T;
  nurtureStage?: T;
  nurtureOptOut?: T;
  nurtureLastAt?: T;
  marketingOptOut?: T;
  adCampaign?: T;
  adGroup?: T;
  adKeyword?: T;
  adGclid?: T;
  dealStatus?: T;
  dealPackage?: T;
  dealValue?: T;
  dealMonths?: T;
  dealClosedAt?: T;
  dealNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contracts_select".
 */
export interface ContractsSelect<T extends boolean = true> {
  title?: T;
  status?: T;
  contractType?: T;
  horizonte?: T;
  valorMensal?: T;
  projNome?: T;
  projDescricao?: T;
  etapas?:
    | T
    | {
        nome?: T;
        prazo?: T;
        descricao?: T;
        id?: T;
      };
  projDuracao?: T;
  projDataEntrega?: T;
  projValorTotal?: T;
  projParcelas?: T;
  projValorParcela?: T;
  tipoPessoa?: T;
  pfNome?: T;
  pfCpf?: T;
  pjRazao?: T;
  pjFantasia?: T;
  pjCnpj?: T;
  pjRepNome?: T;
  pjRepCpf?: T;
  pjRepCargo?: T;
  clienteEndereco?: T;
  clienteEmail?: T;
  clienteTelefone?: T;
  dataInicio?: T;
  diaVencimento?: T;
  formaPagamento?: T;
  clausulaReajuste?: T;
  temDiagnostico?: T;
  diagValor?: T;
  diagData?: T;
  diagForaPrazo?: T;
  bonusMesGratis?: T;
  bonusVisitaExtra?: T;
  bonusIndicacao?: T;
  indicacaoPerc?: T;
  bonusIsencaoMulta?: T;
  bonusParcelamento?: T;
  parcelamentoN?: T;
  paragrafoLivre?: T;
  localAssinatura?: T;
  dataAssinatura?: T;
  contractHtml?: T;
  contractHash?: T;
  signToken?: T;
  additionalRecipients?:
    | T
    | {
        nome?: T;
        email?: T;
        telefone?: T;
        sentAt?: T;
        id?: T;
      };
  signedAt?: T;
  signerIp?: T;
  signerNameConfirmed?: T;
  signerDocumentConfirmed?: T;
  signatureHashAtSigning?: T;
  signerMismatchAcknowledged?: T;
  signedPdf?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contract-documents_select".
 */
export interface ContractDocumentsSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "email-segments_select".
 */
export interface EmailSegmentsSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  source?: T;
  pillar?: T;
  scoreMin?: T;
  scoreMax?: T;
  createdFrom?: T;
  createdTo?: T;
  memberCount?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "email-campaigns_select".
 */
export interface EmailCampaignsSelect<T extends boolean = true> {
  subject?: T;
  segment?: T;
  body?: T;
  status?: T;
  statsTotal?: T;
  statsSent?: T;
  statsFailed?: T;
  statsStartedAt?: T;
  statsFinishedAt?: T;
  statsError?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "email-logs_select".
 */
export interface EmailLogsSelect<T extends boolean = true> {
  type?: T;
  status?: T;
  to?: T;
  subject?: T;
  lead?: T;
  campaign?: T;
  via?: T;
  errorMessage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ad-campaigns_select".
 */
export interface AdCampaignsSelect<T extends boolean = true> {
  name?: T;
  googleAdsCampaignId?: T;
  status?: T;
  dailyBudgetTarget?: T;
  monthlyBudgetTarget?: T;
  cpcCeiling?: T;
  startDate?: T;
  notes?: T;
  forecastClicks?: T;
  forecastImpressions?: T;
  forecastCost?: T;
  forecastCtr?: T;
  forecastAvgCpc?: T;
  forecastDailyBudget?: T;
  forecastCapturedAt?: T;
  forecastNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ad-groups_select".
 */
export interface AdGroupsSelect<T extends boolean = true> {
  campaign?: T;
  name?: T;
  status?: T;
  rollupWindowDays?: T;
  rollupImpressions?: T;
  rollupClicks?: T;
  rollupCost?: T;
  rollupConversions?: T;
  rollupUpdatedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ad-keywords_select".
 */
export interface AdKeywordsSelect<T extends boolean = true> {
  campaign?: T;
  adGroup?: T;
  text?: T;
  isNegative?: T;
  negativeLevel?: T;
  matchType?: T;
  status?: T;
  rollupWindowDays?: T;
  rollupImpressions?: T;
  rollupClicks?: T;
  rollupCost?: T;
  rollupConversions?: T;
  rollupUpdatedAt?: T;
  plannerVolume?: T;
  plannerCompetition?: T;
  plannerTopBidLow?: T;
  plannerTopBidHigh?: T;
  plannerYoY?: T;
  plannerCapturedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ad-metrics-daily_select".
 */
export interface AdMetricsDailySelect<T extends boolean = true> {
  campaign?: T;
  date?: T;
  impressions?: T;
  clicks?: T;
  cost?: T;
  conversions?: T;
  source?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ad-competitors_select".
 */
export interface AdCompetitorsSelect<T extends boolean = true> {
  name?: T;
  domain?: T;
  keywordText?: T;
  type?: T;
  adTitle?: T;
  adSnippet?: T;
  appearances?: T;
  seenAt?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "system-links_select".
 */
export interface SystemLinksSelect<T extends boolean = true> {
  name?: T;
  url?: T;
  description?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "api-inventory_select".
 */
export interface ApiInventorySelect<T extends boolean = true> {
  name?: T;
  provider?: T;
  category?: T;
  systems?:
    | T
    | {
        system?: T;
        envVar?: T;
        active?: T;
        id?: T;
      };
  status?: T;
  expiresAt?: T;
  renewalCycle?: T;
  hasBilling?: T;
  billingType?: T;
  balanceOrCost?: T;
  balanceCheckedAt?: T;
  billingLink?: T;
  credentialLocation?: T;
  notes?: T;
  lastVerified?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "content-calendar_select".
 */
export interface ContentCalendarSelect<T extends boolean = true> {
  date?: T;
  phase?: T;
  pillar?: T;
  channels?: T;
  format?: T;
  theme?: T;
  sourceLabel?: T;
  copyIdea?: T;
  ctaOrAction?: T;
  status?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        feature?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ads-settings".
 */
export interface AdsSetting {
  id: number;
  /**
   * Gerado automaticamente ao conectar com o Google no painel. Valor oculto por segurança — reconecte em "Conectar Google Ads" para gerar um novo.
   */
  refreshToken?: string | null;
  lastSync?: string | null;
  /**
   * A API do Google Ads só expõe limite de gastos quando ele foi explicitamente configurado — contas pré-pagas self-serve normalmente ficam "sem_limite".
   */
  budgetStatus?: ('com_limite' | 'sem_limite' | 'indisponivel') | null;
  budgetApprovedLimit?: number | null;
  budgetSpent?: number | null;
  budgetRemaining?: number | null;
  budgetSyncedAt?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ads-settings_select".
 */
export interface AdsSettingsSelect<T extends boolean = true> {
  refreshToken?: T;
  lastSync?: T;
  budgetStatus?: T;
  budgetApprovedLimit?: T;
  budgetSpent?: T;
  budgetRemaining?: T;
  budgetSyncedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}